### ISSUE TITLE
Missing GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by derekperkins** [edrevo/suspicious-pods#2]
It's not consistent, but sometimes I get this error, even when the command ran just previously, and I can always use `kubectl` without errors.

```
Error: Error { inner:

Error loading kube config: Missing GOOGLE_APPLICATION_CREDENTIALS env }
```

**Comment by edrevo** [comment]
Could you share an (expired) kubeconfig that you have seen that has reproduced this error? Also, do you have that env var set?

**Comment by edrevo** [comment]
Closing as stale. Please reopen if you still reproduce this error in the 1.0 release. Thanks for the report!

**Comment by derekperkins** [comment]
The error printout got a little nicer with 1.0, but the same outcome.

```
suspicious-pods --all-namespaces
Error: KubeConfig("Missing GOOGLE_APPLICATION_CREDENTIALS env")
```

I do not have that env var set. It is a well-known var that Google checks for in various default credential paths. I have a few other Kubernetes tools like Lens that use my kubectl context without error. Here's a redacted kube config:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: qwerty
    server: https://1.2.3.4
  name: gke_my-cluster
contexts:
- context:
    cluster: gke_my-cluster
    user: gke_my-app
  name: nozzle
current-context: nozzle
kind: Config
preferences: {}
users:
- name: gke_my-app
  user:
    auth-provider:
      config:
        access-token: abc
        cmd-args: config config-helper --format=json
        cmd-path: /Users/derek/google-cloud-sdk/bin/gcloud
        expiry: "2020-04-09T18:31:47Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
