### ISSUE TITLE
 ReqwestError

### ISSUE THREAD

**Issue by leiyang** [edrevo/suspicious-pods#5]
on my ubuntu os 
Error: ReqwestError(reqwest::Error { kind: Request, url: Url { scheme: "https", host: Some(Ipv4(122.*.*.*)), port: Some(6443), path: "/api/v1/namespaces/default/pods", query: Some(""), fragment: None }, source: hyper::Error(Connect, Custom { kind: Other, error: "invalid dnsname" }) })

**Comment by Dentrax** [comment]
I'm getting exactly same error with macOS. @edrevo 

```bash
$ suspicious-pods --version

suspicious-pods 1.1.0
```


```bash
$ KUBECONFIG=/Users/furkan/.kube/config-foo suspicious-pods

Error: ReqwestError(reqwest::Error { kind: Request, url: Url { scheme: "https", host: Some(Ipv4(10.X.XX.XXX)), port: Some(XXXX), path: "/api/v1/namespaces/default/pods", query: Some(""), fragment: None }, source: hyper::Error(Connect, Custom { kind: Other, error: "invalid dnsname" }) })
```

```bash
$ KUBECONFIG=/Users/furkan/.kube/config-foo kubectl get --raw='/readyz?verbose'

All is OK.
```

**Comment by edrevo** [comment]
Thanks for the report! Could you share an expired kubeconfig? I am trying to understand what difference between your kubeconfigs and mine might be causing this. Are you using a DNS for the server or an IP?

**Comment by Dentrax** [comment]
Looks like this:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXX
    server: https://10.XX.XXX.XXX:XXXX
  name: foo
contexts:
- context:
    cluster: foo
    namespace: my-namespace
    user: kubernetes-admin
  name: kubernetes-admin@foo
current-context: kubernetes-admin@foo
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    token: XXX
```
